language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.5
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
install:
  - "pip install --use-mirrors Django==$DJANGO_VERSION"
  - "pip install --use-mirrors south"
  - "pip install --use-mirrors --editable ."
script: "django-admin.py test --settings=gubbins.tests.settings gubbins"
